### ISSUE TITLE
Ankaios server builds and maintains a dependency graph

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#136]
## Description

The Ankaios server shall maintain a dependency graph for the workload dependencies. It shall detect cycles in the dependency config and reject an invalid config containing cycles.

## Goals

The Ankaios server shall support workload dependencies and reject invalid dependency configuration.

### Tasks

- [x] Ankaios server can detect cycles in the startup state and rejects states with a cycle by exiting with an error containing the - names of the workloads building the cycle.
- [x] Ankaios server can detect cycles introduced by a set state and rejects the state
- [ ] ~~When Ankaios server rejectes a state because of cycles introduced by a set state the server shall respond with a corresponding message (we need the changes from https://github.com/eclipse-ankaios/ankaios/issues/13 for this)~~ This will be done with #13

**Comment by inf17101** [comment]
For dependency graph representation the already existing data structure `CompleteState` inside the Ankaios server is used. There is no need to introduce a separate data structure currently to represent the dependency graph and to search for cycles. This data structure represents the graph already in a adjacency list style that is suitable for directed graph representation. The adjacency list has the form `HashMap<WorkloadName, HashMap<Dependency Workload Name, AddCondition for Dependency>>` (simplified presentation and part of the CompleteState).

There are several algorithms to detect a cycle in a graph:
- Johnson's algorithm https://www.cs.tufts.edu/comp/150GA/homeworks/hw1/Johnson%2075.PDF
- Floyd's tortoise and hare algorithm
- Brent's algorithm
- Breath first search (BFS)
- Depth first search (DFS)

The decision is to go with classical DFS because we have only mid sized graphs for dependency (we do not expect to have a config with 20 Mio workloads...). It is a common algorithm for detecting cycles and very well engineered. With DFS we can at least find one cycle if we make sure that we visit all the nodes. It finds cycles in linear time complexity (O(|V| + |E|) where V are the amount of vertices and E the amount of Edges, which means we must visit all vertices and edges in the worst case, so going through the whole graph ones). On top of that DFS is easy to understand compared to other algorithms.
Johnson's algorithm is very fast and suitable for large graphs with a lot of cycles it can find all cycles by dividing the graph into multiple sub graphs and doing DFS afterwards. This algorithm sounds too overengineered for our basic cyclic detection purposes with not soo much workloads (vertices). Floyd's and Brent's algorithms are very storage efficient and are based on moving pointers. They are really interested but do not fit very well to our current `CompleteState` hashmap structure so that integer based representation of the graph must be calculated first. To map the current graph into another data structure or representation costs also time and a lot of extra steps. So as a compromise between speed and re-using existing data structures the DFS is enough.

**Comment by inf17101** [comment]
There are four typically known algorithms for cycle detection with DFS:
- recursive DFS with path array (also known as recursionStack)
- iterative DFS with stack and path array
- recursive DFS with coloring vertices
- iterative DFS with colored vertices

The iterative DFS are fitting more the embedded system use cases because it has lower cost on memory (stack size) in the worst case and recursive algorithms can lead to stack overflows in worst case scenarios. It was looked into the assembly code of the recursive DFS impl generated by Rust compiler and the Rust compiler does not an elimination of the recursion because the algorithm is not tail recursive.

Next, I compared the iterative DFS with stack and path array with the iterative DFS colored approach. The result was that with our current data structures the iterative DFS with stack and array is faster in debug and release mode:
Debug:
![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/ad9c7793-2e5b-451e-9346-8e820294b1c7)
Release:
![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/be88485c-cb98-493d-b980-e036223b85e7)

**Comment by inf17101** [comment]
If the implemented DFS algorithm detects a cycle within the graph then the path array contains the path of the cycle. To not spam the error message output with the whole path to the user, we decided to just mention the workload name that is part of the cycle, for example: `cycle in dependencies detected: workload 'hello1' is part of cycle.`

**Comment by inf17101** [comment]
To finish the ticket I am waiting on #13. But meanwhile, I can continue with the queue implementation in the agent.

**Comment by krucod3** [comment]
Done.
