### ISSUE TITLE
Major updates of the Ankaios state

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#164]
## Description

The following major updates need to be done on the Ankaios complete state:
* the "current state" object must be renamed to "desired state" as the current name gives the wrong impression that this is what is currently running.
* add versioning to the config: at least the complete state should get a version; adding a version to the workload config could also be done, but makes things more complicated
* unimplemented features should be removed to reduce confusion:
  * startupState.configs
  * startupState.coronJobs
  * startupState.workloads.updateStrategy
  * startupState.workloads.accessRights
* add a "migration guide" to the user documentation in case of breaking change (what the user needs to do to upgrade his config).

## Goals

Make the Ankaios config easier to understand and support future updates.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] rename the current state #171 
- [x] add versioning to the config
- [x] remove unimplemented features
- [x] check the user documentation (updates, the migration guide) - will be done in #184

**Comment by windsource** [comment]
Just for clarification: the version of the config shall be a format version and not a content version. So the version of the config will be increased whenever the format changes (e.g. with a new release of Ankaios).

**Comment by maturar** [comment]
To rename the current state into the desired state also includes:
* update tests
* update requirements (names, description, mapping)
* update the user documentation
* update examples

**Comment by maturar** [comment]
**Regarding versioning:**
The idea is when we get a complete state over the Control Interface (from the `ank set state` for example), we have to validate that the config matches to the code (what the code expects to get).
More less it means to add new member `format_version` to the object with the CompleteState. There is a crate with the semantic versioning in the Rust:
https://docs.rs/semver/latest/semver/struct.Version.html
The difficulty of this crate is that it requires to have always the patch version. We would like to have only a major and minor version. It is necessary to doublecheck the crate if we can skip the patch version. Another alternative would be to find another crate or write our own structure.

**Comment by maturar** [comment]
**Regarding unimplemented features:**
The ticket description says that we shall remove items from the `startConfig`, but in the reality it means also remove these items from the `desiredState`.
Background information: We use the same structure for the startConfig and desiredConfig. Therefore if we remove an item from the one state, it is also removed from the other (and this is what we actually want here).

**Comment by maturar** [comment]
This is the format of the CompleteState **including all changes** requested in this ticket:
```
formatVersion:
  major: 0
  minor: 1
startupState:
  workloads: {}
desiredState:
  workloads: {}
workloadStates:
- ...
```
The changes are:
- currentState renamed into desiredState
- new field `format_version`
- removed unused items (configs, cronJobs).

The most questionable change is the `format_version`. The alternative could be that the major and minor version is defined as a string. Something like: `format_version: "0.1"`. Disadvantages of this approach are that we need a parser in the code and we have to handle strings like "0.1.1" or "0.1.1-alpha" (unsupported format or ignore everything except of the major and minor version?). For me it easier to define the format_version as proposed above.

**Comment by maturar** [comment]
Additionally the Server has to answer error to the UpdateState request if the format version does not match. It is not okay to answer nothing. Current main branch shall be able to support this already.

**Comment by maturar** [comment]
The implementation has been finished. The ticket is ready for review.

**Comment by maturar** [comment]
The pull request has been reviewed and merged to the main branch.
