### ISSUE TITLE
Fix the test coverage for implementation enhancements of Rust's channels

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#168]
## Description

There are impl blocks for extending a Rust channel in the code base,
that must be excluded from coverage if a test is too trivial (because it is not needed to test the std library behavior of Rust)
or tests must be written for them to satisfy the coverage.

**Example where unit tests are written to test the trivial Rust channel behavior the satisfy coverage:**
[common/src/to_server_interface.rs](https://github.com/eclipse-ankaios/ankaios/blob/main/agent/src/workload.rs)

**Example where no tests are written:**
common/src/from_server_interface.rs

There are potentially more code paths with the same issue or mixture.

## Goals

Have a single solution for dealing with such scenario. Document the decision in the developer guide.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Search through the code base where trivial implementations like Rust channels are tested or not tested
- [ ] Discuss solution with Architect @krucod3 or @christoph-hamm to decide whether to exclude them from coverage or to write unit tests to satisfy test coverage.
- [ ] Add or remove tests according to the result of the discussion and document it for future use in developer guide or contribution guide.

**Comment by krucod3** [comment]
Will be done with #259
