### ISSUE TITLE
Plantuml update inside devcontainer

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#179]
## Description

The devcontainer contains a very old version (1.2020.02) of plantuml having a bug with the "++--" syntax.
This causes issues in activation sequences of changes in uml sequence diagrams in #177.

In the preview mode of VSCode, the extension uses an own defined version 1.2022.x, which does not have the bug and generates the diagram correctly. The binary inside the devcontainer is older and has the bug with the wrong lifetimes.

## Goals

Upgrade plantuml to latest that does not have the bug.

### Summary

The plantuml version inside the devcontainer was updated to the current latest one: 02.2024.
The plantuml preview vscode extension setting was changed to use the binary inside the devcontainer to generate the preview during development. This ensures equal and consistent diagram output for all developers and environments where the devcontainer runs.

### Tasks

- [x] Find a newer version that has not the bug (latest)
- [x] Integrate the new version into the devcontainer
- [x] Create a setting inside .vscode/settings.json to enable the extension to use the plantuml jar from the devcontainer to have equal development experience for all users
- [x] Test and push a new devcontainer base image
