### ISSUE TITLE
Remove confusing test combinations of PodmanUtils

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#18]
Reported by @inf17101:

## Description

Currently, when ever the test setup function `generate_list_container_with_state(...)` inside `agent/src/podman/podman_utils.rs` is used when testing the `convert_podman_container_state_to_execution_state(...)` function, there are confusing combinations.

Function signature: 
```
    pub fn generate_list_container_with_state(
        exit_code: Option<i32>,
        exited: Option<bool>,
        state: Option<String>,
    );
```

For example, the test passes if the function is setup with the following arguments: `generate_list_container_with_state(ec_success, finished, Some("Created".to_string()));`

Meaning the exit_code is success (0), the container is finished (true) and the state is "created", which is a confusing container state setup in general.

The point why this test is passing is that any string that is different form "exited" is ignored by `convert_podman_container_state_to_execution_state(...)`, because it only listens to "exited", but does not care about other strings passed into the setup method before.

Maybe the `generate_list_container_with_state(...)` can determine the state according to the first two arguments automatically,
then there is no need to have this as third extra argument, causing different confusing test combinations.
Making the API design of this test function less error prune and easier. But this must be analyzed and checked within this issue.

Furthermore it is not clear if the tests are testing the correct thing, podman api might return.

## Goals

Simplify the test setup to have unique and clean way to setup the correct state expected for the testing `convert_podman_container_state_to_execution_state(...)` function. Furthermore introduce correct tests handling the podman api return values correctly.

## Tasks

- [ ] Remove confusing argument combinations / rethinking the test setup method design
- [ ] Check the implementation of `convert_podman_container_state_to_execution_state(...)` if it handles the desired situation of returned by podman api correctly
- [ ] Introduce new tests or change existing tests

**Comment by maturar** [comment]
We have changed podman runtime significantly in the issue #1. Check whether there is something to do here or not.

**Comment by maturar** [comment]
The file `agent/src/podman/podman_utils.rs` has been removed completely in #1. The new implementation is different -> I am closing the issue as not planned.
