### ISSUE TITLE
Create integration test concept and add first tests

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#19]
Reported by @inf17101:

## Description

After developing features / changes, the developer has to test manually with the ank binaries, to make sure that no existing behavior was broken by the changes.
To focus on developing and testing the new feature it would be great to have integration tests covering the existing functionality.

Maybe we can also measure the time from starting Ankaios till the runtime is triggered and compare this with a previous run to see if there are performance degradations (see also #3).

## Goals

Create an integrationtest concept for automatic testing the ank binaries and also the public apis of the project.
The tests shall be executable on CI/CD environment (Github Actions).

## Tasks

- [x] Create integration test concept for testing user cli usage (Maybe Python calling ank cli and podman...) -> Decided by team to use Robot framework for integration and system tests
- [x] Create integration test concept for testing public APIs of the codebase (Maybe Rust) -> Decided by team to use Robot framework for integration and system tests
- [x] Adding integration tests for existing features (create more tickets for adding integration tests that cannot be done inside this issue) #52, rest will be handled with #56
- [x] Integration of Robot framework and Podman in devcontainer #52
- [x] Restructuring of the python lib code #52
- [x] Requirements tracing #52
- [x] Improving logging for better debugging #52
- [x] Adding documentations (usage, guidelines for writing itests) #52

**Comment by windsource** [comment]
Do we need Podman for running the integration tests? In that case they would need to be executed outside of the devcontainer as we do not have Podman in it. I have just tried to install Podman in the dev container but it pulls in systemd as well and did not run out of the box. Not sure if we want Podman in the dev container.

**Comment by inf17101** [comment]
It would be desirable to have an environment that is possible to re-use in CI/CD context. This means a container image containing all the needed dependencies (python3, ...) and runtimes (podman, ...) would be nice to have.

If we include the runtimes in the devcontainer then we have a big sized container image, which grows whenever a new runtime is added and tested.

On the other hand, to have all in one in a single devcontainer enables developers to execute tests very often, because there is no need to switch to other containers. So, there is no barrier to execute the integration-tests very often.

@lingnoi and I are still in discussion, figuring out what is the best compromise between "easy test execution" and having "not too big containers".

**Comment by lingnoi** [comment]
After discussions we agreed on using the Robot framework for writing system tests and integration tests. The Robot framework and podman will be integrated into the the devcontainer to be able to executing the tests during the development.
