### ISSUE TITLE
Format version for workload state in complete state, startup config and ank-apply-manifest

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#193]
## Description

We need a version for the Ankaios configuration files that helps users see if the configs they are using are compatible with the used Ankaios version.

We tried adding a format version to the complete state, but two more places use an Ankaios config without a version:
* startup config file
* `ank apply`

The startup config file actually kind of remain as is after the initial PoC and is at the end the content of the startupState section of the  complete state. The `ank apply` manifest is based on the same format, but allows empty agents in case the user specifies a --agent flag at the CLI.

We have the following possibilities:
| option | comment | outcome |
| -- | -- | -- |
| Add a format version also to the startup config file and to the `ank apply`  manifest | At the end we would have 3 version this way - one for every config file type. Additionally the implementation would be more complicated as the version would need to be compared at one placed, then skipped in the deserialization, etc.| ❌ |
| Add a version for the workload config. As the workloads field is an array, the version needs to be under every workload | This would bloat the file and is error prone when merging configs | ❌ |
| Leave a version only for the complete state and have no version for the startup state | Very inconsistent... | ❌  |
| We could add a workload version under state. | This would allow also having a separate version for configs, but on the other hand makes things very complex and with a lot of versions that we don't (yet) need | ❌  |
| Change the startup state config to actually look like a complete state with `startupState: workloads: ...` and add the config as for the complete state as a top level element | `ank apply` already uses the format (which was unintentionally followed for startup) and it was undesired to change this | ❌ |
| Add a format version for the state in the complete state. This version needs to be written for both startup and desired state. in the complete state| As it has to be written in both places is is a bit error prone, but on the other hand the state is indeed the config used as a startup state, manifest and in the compete state. | ✔️  |

❗ Please note that the ticket is only targeted at the complete state, the ank-apply-manifest and the startup config.
Ankaios still does not have a protocol version for the Control Interface. The protocol version for the Control Interface must be added later via a separate ticket.
❗ Please also note that the version for the configs will initially handled as a plain string in the form `v0.1`. We don't need a full semantic version as patch updates make no sense for a configuration file. We need to clarify if we want to support a minor version too. The `v` in front of the version can in theory also be removed when we make an official production release, but for now helps identify the string as a version (by a human).
❗ Please also note that the `workloadStates` section will also not get a version now. Maybe later when we version the protocol (control interface)

## Goals

Add a version for the Ankaios configuration files that helps users see if the configs they are using are compatible with the used Ankaios version.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] Update format version in the `CompleteState` -  #197 
- [x] Add version to the `startConfig`.
- [x] Add version to the `manifest.yaml`.
- [x] Check/update user documentation.
- [x] Clarify with the team whether we would like to have major **and minor** version on the format version.
- [x] Rename `formatVersion` to `apiVersion`
- [x] Return/request `apiVersion` only for the request without filter mask

**Comment by maturar** [comment]
Additionally we have agreed to define the format version (in yaml) like this:
```yaml
formatVersion: "v0.1"
```
Currently in the main the format version is defined like this:
```yaml
formatVersion:
  version: "v0.1"
```

**Comment by maturar** [comment]
It has been decided with the team to rename the `formatVersion` to `apiVersion`. Content stays the same. A string which the server takes and compares with the current version. Identical strings -> config accepted, non-identical strings -> config rejected.

**Comment by krucod3** [comment]
For get state with filter masks we can omit attaching the version as an extra step if the version was not included in the path. This way we simplify the implementation and reduce the risk that somebody get an "incomplete" state with a filter mask and applies it without filter mask using default values.
@windsource, what do you think about it?

**Comment by krucod3** [comment]
@windsource, we have this already: `ank get state desiredState` this will return the whole manifest including the version.

**Comment by windsource** [comment]
@krucod3 But in that case `desiredState` is the filter mask, or? So we will check what kind of filter mask is provided (i.e. the level)?

**Comment by krucod3** [comment]
@windsource, the idea is, the version is provided and is required if it is in the scope of the filter mask. This also makes the implementation straight forward. No filter mask just means match everything.

**Comment by windsource** [comment]
@krucod3 So will it be like that?

| command | apiVersion is returned |
| ----------- | ------------------------ |
| `ank get state desiredState` | yes |
| `ank get state desiredState.workloads` | yes |
| `ank get state desiredState.workloads.nginx` | yes |
| `ank get state desiredState.workloads.nginx.agent` | no |

**Comment by krucod3** [comment]
Currently we have the following structure of the complete state returned (and required) by the get (set) state functions in both the ControlInterface and the `ank` CLI:
``` json
...
startupState:
  workloads: {}
desiredState:
  apiVersion: "v0.1"
  workloads:
    nginx:
...
```
The filter mask will just filter from this structure, meaning a filter mask desiredState.workloads will not return the apiVersion as it is outside the filter mask.
=> Only the first roll in the table is correct

**Comment by maturar** [comment]
The pull request has been reviewed and merged into main.
