### ISSUE TITLE
Bash auto completion for ank CLI

### ISSUE THREAD

**Issue by christoph-hamm** [eclipse-ankaios/ankaios#237]
## Description

We should write an auto completion script for bash, to make the usage for the ank CLI easier.

## Goals

Add auto completion script.

### Summary

Shell completion has been implemented using `clap_complete`. See [documentation](https://eclipse-ankaios.github.io/ankaios/main/usage/shell-completion/) about how to use it in Ankaios. There is one part not working which is `ank set state` when entering an object field mask there is no completion for a state file which has to be fixed in https://github.com/clap-rs/clap/issues/5701.

### Tasks

- [x] Auto completion for command names 
- [x] Auto completion for workload names (only where workload names are used)
- [x] Auto completion of filenames (only where filenames are used)

**Comment by windsource** [comment]
Maybe we can add support for zsh autocompletion as well.

**Comment by windsource** [comment]
See also [Clap CompleteCommand](https://docs.rs/clap_complete/latest/clap_complete/dynamic/shells/enum.CompleteCommand.html) which seems to be work in progress.

**Comment by windsource** [comment]
For dynamic completion the following use cases exist:

* `ank get workload <workload_name(s)>`
* `ank delete workload <workload_name(s)>`

Maybe also for `object_field_mask` which is used in

* `ank get state`
* `ank set state`

Also the agent name might be completed in

* `ank get workloads --agent`
* `ank run workload --agent`
* `ank apply --agent`
