### ISSUE TITLE
Delete startupState from CompleteState

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#242]
Currently `CompleteState` contains the `startupState` but it not handled which is confusing for users. `ank get state` returns and empty `startupState` even when the real startup state was not empty.

For this reason the  `startupState` shall be removed from the `CompleteState`.

## Goals

Remove the  `startupState` from the `CompleteState` to not confuse the user when calling `ank get state`.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] Remove the state from the source code
- [x] Fix tests
- [x] Update user documenation
- [x] Check requirements and SwDDs
- [x] Check examples

**Comment by maturar** [comment]
The PR with the implementation has been reviewed and merged into main.
