### ISSUE TITLE
Provide releases of documentation

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#25]
## Description

Currently the documentation website always shows the latest version for main branch. This can and will differ from previous releases.

## Goals

Users shall be able to select a revision for the website they want to see. MkDocs Material already [supports that](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/) using [mike](https://github.com/jimporter/mike).

## Tasks

- [x] Get familiar with mike
- [x] Add mike to devcontainer-base and push new image
- [x] Update scripts and mkdocs.yaml
- [x] Update Github Actions
- [x] Check for hard coded links that are affected by version in URL
- [x] Add build of documentation to release build
- [x] After PR got merged, prepare mike (see below)

**Comment by windsource** [comment]
Am example is provided here: https://github.com/squidfunk/mkdocs-material-example-versioning.

**Comment by windsource** [comment]
After the PR got merged the following steps need to be performed:

```
 # Delete old documentation
mike delete --all
# Generate "latest" version
git pull origin main
git checkout main
mike deploy latest
# Generate "0.1" version
git checkout v0.1.0
mike deploy 0.1
# Set default version and push
mike set-default latest --push --force
```

**Comment by windsource** [comment]
- The build from main should be shown as `unstable` version
- Building a release should result in major.minor (e.g. tag `v0.1.0` results in the documentation version `0.1`)
- By default the documentation of the latest release should be shown

**Comment by windsource** [comment]
The build from main should be shown as `main` version.

A preview of the new documentation is available on https://windsource.github.io/ankaios/.
