### ISSUE TITLE
Yocto Project meta-layer or Recipe under Meta-Virtualization Layer for Ankaios

### ISSUE THREAD

**Issue by mrogonna** [eclipse-ankaios/ankaios#272]
## Description
The goal of this issue is to create a `meta-layer` or `recipe` and incorporate it into the `meta-virtualization` layer for Ankaios within the Yocto Project. The Yocto Project is an open-source collaboration project that helps developers create custom Linux-based systems regardless of the hardware architecture. This enhancement will allow the developer to customize their process to fit their specific use case.

## Goals
1. Develop a Yocto Project `meta-layer` or `recipe` for Ankaios.
2. Enable developers to customize their build chain.
3. Improve the software development process for embedded Linux distributions.

## Final result
The final result should be a fully functional Yocto Project `meta-layer` or `recipe` for Ankaios that developers can use to customize their build chain. This will provide a flexible and efficient way to manage and deploy Ankaios in various automotive use cases.

### Summary

**To be filled when the final solution is sketched.**

### Tasks
- [x] Design and implement the `meta-layer` or `recipe`
- [x] Document the usage of `the meta-layer` or recipe.
- [x] Release the meta-layer or recipe for public use.

**Comment by simone-weiss** [comment]
Hi, just a side note: there is bitbake cargo that will write the recipe for the local crate. That might give you a good starting recipe already.

**Comment by kishorebhadra** [comment]
Hi everyone,

We would like to contribute to this task .
Is there any additional information or recommendations we should know before starting to contribute?

Best Regards
Kishore

**Comment by krucod3** [comment]
Hi Kishore,

thank you for your interest in Ankaios 😃 
The issue here was created by @mrogonna as he was interested in writing the recipe. 
To avoid double work, we have to sync and see what the current state on his side is. 
If he needs some help or does not have the time currently, it would be great if you can help.

@mrogonna, can you please shed some light here? Thanks you!

Br,
Kaloyan

**Comment by mrogonna** [comment]
Hello Kishore,

Thank you for your interest to work on this issue,
I already started work on it and have created the recipe locally, However, due to a parallel project, I had temporarily paused further tasks such as documentation and other modifications.
I think it would be a good idea to sync together and discuss what has been done and possible improvements and also align with @krucod3 before we finally publish it.
what do you think?

Regards,
Ogonna.

**Comment by kishorebhadra** [comment]
Hello Ogonna,

Definitely, we can sync up and discuss the progress made and explore possible improvements and determine how we can support you.

Regards,
Kishore

**Comment by windsource** [comment]
For getting in contact there is also the Ankaios Slack workspace: https://eclipse-ankaios.github.io/ankaios/latest/support/.

**Comment by mrogonna** [comment]
Hello @kishorebhadra 
please join the slack workspace https://app.slack.com/client/T073UJBN81E/C073UJBTN00 and write me so we can align 
Regards,
Ogonna

**Comment by krucod3** [comment]
Today we had a sync with @mrogonna and discussed the following topics:
* The versions in the individual Ankaios packages are currently imported from the workspace. We did this for convenience, but it is a problem for the bitbake build. We will look into this with #325 
* The poky yocto layer provides runstc and cargo in version 1.59.0. @mrogonna worked around this by using the meta-rust layer and masking poky. In theory we could look into adding support for older compiler versions, but in the long run it's better to use the newest compiler.
* @mrogonna needed to add some extra dependencies for protobuf to the recipes
* publishing: to make the recipe available as soon as possible @mrogonna will first publish in his own repo. For later it would be a good idea to publish the recipe in https://github.com/eclipse-leda/meta-leda. @mrogonna will create an issue for this in the repo.

**Comment by mrogonna** [comment]
Update on this issue:

- I published the recipes in the following git repo [meta-ankaios](https://github.com/mrogonna/meta-ankaiosl) and Added the documentation on how to generate the recipes from the source.
- I forked the `eclipes-ankaios` repo and modified the individual ankaios packages, this could be used as the [source](https://github.com/mrogonna/ankaios) to generate new recipes till this issue [Versions of individual Ankaios packages](https://github.com/eclipse-ankaios/ankaios/issues/325) is resolved.
- I created a ticket [Incorporate Eclipes Ankaios Recipes under meta-leda](https://github.com/eclipse-leda/meta-leda/issues/212) project to integrate `ankaios-recipes` on `meta-leda` . @krucod3 you can also add a comment on the `meta-leda` ticket if there are additional information I missed

**Comment by krucod3** [comment]
Hi @mrogonna, the work here is actually done now, right? If so maybe we can close the issue. Thanks a lot

**Comment by mrogonna** [comment]
This issue has been resolved, the following are done:

- The ankaios recipes are generated
- Documentation to generate recipes from source
- Proposal to integrate it with Eclipse-Leda project
