### ISSUE TITLE
Provide Python SDK for accessing the control interface

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#304]
## Description

Provide libraries to simplify the access to the control interface from workloads.

## Goals

* provide library for Python

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] Draft a first version
- [x] Review
- [x] Release an RC
- [x] Fix logo links
- [x] Add versioning guide
- [x] Add the documentation as GitHub pages
- [x] Investigate on adding badges with utests, coverage, py version, slack, license
- [x] Update the "documentation" link in the sdk to point to the correct doc
- [x] Add link from the GitHub README.md to the PyPi package
- [x] Test thoroughly that everything works (i.e., in general and also install on different OSs)
- [x] Fix the release/publish workflows
- [x] Release the real 0.5.0 (please note, no "v")
- [x] prepare the proto retrieval mechanism for the official release
- [x] Release the 0.5.0-rc3

**Comment by GabyUnalaq** [comment]
This issue is blocked until a concept is found.
Issue: https://github.com/eclipse-ankaios/ankaios/issues/376

**Comment by GabyUnalaq** [comment]
Fork: https://github.com/GabyUnalaq/ank-sdk-python

**Comment by krucod3** [comment]
Here are some scenarios where the SDKs will be used:
* implement a CLI (at some point we will need to switch our CLI to use the SDK, but first the SDK has to support also the gRPC interface which has no priority now)
* implement a cloud connector as a workload which helps achieve a fleet management workflow
* implement a multistage startup process where one workload is started as a first one and it starts the rest of the system in a predefined way
* watchdog workloads

In most of the scenarios the use-cases are very similar:
1. update the cluster and monitor 
2. monitor and take action (by logging to the outside world and updating the cluster)

Currently Ankaios does not support events (but we plan to) so monitoring boils down to polling for now. The gRPC interface also provides unsolicited messages for the workload states and we will extend the SDK for that interface, but this will be done later.

So use-case 2 is quite easy, if you monitor something, you know the unique Id and you take whatever action you need. 
Use-case 1 is a bit more difficult because if we update a workload, Ankaios will have 2 versions of it for some time and both have the same name. That is why the UpdateWorkload request returns a UpdateStateSuccess message as a response which contains the instance names.

**Comment by krucod3** [comment]
All done here 🥳 
We will continue with the final polishing in dedicated PRs in the sdk repo.
