### ISSUE TITLE
API Unification, Cleanup and Schemas Generation

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#313]
## Description

Currently the server and the ank CLI read a text based configuration (manifest). The CLI can also output the current configuration as json/yaml. The serialization/deserialization is achieved by tagging some Rust structs with serde attributes. 

Since optional data sent over gRPC should be empty and not filled with defaults, we switched to only using the protoBuf generated objects in #22. Annotating them correctly to get a proper result is very hard and requires manual serialization for enums. As a workaround we switched to special objects for the serialization.

We have to unify all objects and develop a strategy how we define our interfaces. At the end we need schemas for the json/yaml data s.t. we are sure the API is fixed.

## Final result

To get a unified and consistent API we created proc and derive macros that allow us to generate the internal spec objects with all mandatory data automatically.

Additionally we annotate the Spec objects with schemars annotations to derive a JSON Schema out of them.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] Implement macros
- [x] remove manually written internal objects and move the still required implementations to the api crate
- [x] check the cli output
- [x] #655
- [x] check the examples
- [x] add dev documentation regarding how the changes to the api should be tackled
- [x] Check the requirements
- [x] update the SDKs
- [x] ~~Fix #595~~
- [x] Find a proper solution for the conversion with defaults for the LogsRequest <-> LogsRequestSpec
- [x] #629
- [x] #641 - Add JSON Schema constraints to make the schema usable for manifest validation
- [x] ~~#620~~
