### ISSUE TITLE
Control interface shall be created only for configured for it workloads

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#322]
## Description

The basic idea here is to skip the creation of the control interface if the configuration of the workload does not contain a control interface field. Doing this will spare some green threads on Ankaios side and the creation of fifo pipes that will never be used, improving the overall performance and stability.

## Goals

* A Control Interface instance shall only be created for configured workloads.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] Rename the PipesChannelContext to something meaningful, like ControlInterface
You can even split this into its own PR and reduce the chances of conflicts with main
- [x] Refactor a bit the creation of the Control Interface and unify the concepts there: Remove the extra functions for creating one; 
- [ ] ...
- [ ] Add an stest that checks that a workload that did not have a ControlInterface access and is updated to have a ControlInterface access is restarted.

**Comment by GabyUnalaq** [comment]
Currently working on this.

**Comment by inf17101** [comment]
The PR for the refactoring is #345.

Notes on the PR:
The ControlInterfaceInfo must be mocked because it is needed in the RuntimeManager where it is constructed within methods. This new call must be intercepted then.

With the new control interface module structure together with mockall implementing a `ControlInterface::from_info` method calling the constructor with the parameters from the Info struct is not testable because a mixture of a mock and not mock inside the same module is not testable. The same is valid for a `try_from` implementation, but anyway a try_from is signaling a type conversion, but we are creating fifo files from an info struct (metadata) which is not type conversion and introduces side effects for the reader.

We decided to refactor to a single method to create an ControlInterface: through its constructor `ControlInterface::new(...)` which is already designed for that. The ControlInterfaceInfo is used as a mock inside the RuntimeManager and also needed there as a mock because its constructor is called within bodies of functions. In general that ControlInterfaceInfo is mocked is making the restructuring more compilcated since it enforces to use also the MockAuthorizer which is a field of the Controlinterface.

With the new structure of the control_interface module there where lots of problems with imports of mocks and public API exports in the module files (public api exports and imports are not allowed inside the same file as the compiler treats it as duplicated imports an throws errors).

Achieved is a common and single interface of creating the control interface in different places where also logging can be handled differently in each client and a new module structure with renamed structures that are now more related to the ControlInterface.

**Comment by krucod3** [comment]
All done here.
