### ISSUE TITLE
Prepare the v0.4 release

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#330]
## Description

This ticket is for tasks (Documentation fixes, link fixes, ...) to prepare the release  build for v0.4.0.

## Goals

A main branch representing the v0.4.0 release with all tasks resolved.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] mTLS improvements and fix of control interface examples, see PR #329 
- [ ] Upgrade the versions inside ankaios-docker setup and test it (First the compose setup must be fixed with "--insecure" in the mtls related PR 329 above)
- [x] Fix spelling mistake in upgrade guide: "messaged" => "messages"
- [x] Add hint that the installing the latest version is not discouraged for automated workflows

**Comment by inf17101** [comment]
I have tested Installaton (with different parameter combination for the install script, and Setup with mTLS), Quickstart, User Tutorial, Examples, and stests on Ubuntu-20.04, Ubuntu-22.04 and Ubuntu-24.04 on vagrant (the 24.04 not with generic image, but with bento distro). No additional findings. All findings are documented in issues or PRs are already opened.

**Comment by krucod3** [comment]
Done.
