### ISSUE TITLE
Make startup config optional for the Ankaios server start

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#34]
## Description

The Ankaios server executable currently requires a startup config to be provided as a command line argument. This is not a hard requirement as the server can start also with an empty startup state. To allow this, we have to make the startup config optional.

Optionally we could also think about accepting standard in for the config.

## Goals

Not requiring a start up config makes it easier to start the Ankaios server. Workloads can be added afterwards via the ank cli.

## Tasks

- [x] update design (incl. requirements)
- [x] make the startup config optional for the server start #132 
- [x] think about allowing standard in for passing the config
- [x] check if we need new system tests
- [x] check if we need to update the user documentation

**Comment by windsource** [comment]
That sounds good and also helps us with #38 as we do not have to provide dummy startup state when installing Ankaios.

**Comment by maturar** [comment]
I am currently checking how to implement the task to read config from the `stdin`. I have checked behavior of our CLI regarding `ank set state` (if it can read from the `stdin` or not). I have noticed interesting behavior. If I run `ank set state currentState` (i.e. set the state without any file given), **it deletes all workloads**. I am not sure, whether this behavior is wanted. Try following script (In the debug folder. It requires a file `startConfig.yaml` to be present) :
```
#!/bin/bash
./ank-server -c startConfig.yaml &
sleep 5
./ank-agent --name agent_A &
./ank-agent --name agent_B &
echo "Waiting for Ankaios to create all workloads"
sleep 30

echo "Setting empty state (without a file)"
./ank set state currentState
sleep 10
echo "Current workloads:"
./ank get workloads

pkill -f ank-
ps -a

echo "Done"
```
The command `./ank get workloads` prints empty table (i.e. no workload in the Ankaios).

The question is how this shall behave and of course how to implement "reading from stdin" in the server. Shall we avoid something like this? Or shall be do it intentionally? Like no configuration via file or stdin given = start "empty server".

**Comment by maturar** [comment]
**To be tested/checked:**
* no config file with startup state
* empty file with startup state

**Comment by maturar** [comment]
Regarding "allowing start config via  stdin". We have discussed in team. Currently we do not plan to let the start config to be configurable via stdin. It is enough to have the start configuration configurable this way:

* with the command line parameter
* no startup configuration and set the configuration from the CLI

**Comment by maturar** [comment]
We need to change/extend following requirement:
https://github.com/eclipse-ankaios/ankaios/tree/main/server/doc/swdesign#server-loads-startup-state-from-a-file

**Comment by maturar** [comment]
The pull request has been reviewed and merged into main.
