### ISSUE TITLE
Automated tests of the user documentation

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#372]
## Description

Prevent wrong user documentation content or invalid links by testing the user documentation automatically.

There is also a package available for the mike package which can test links inside the documentation. This needs to be tested and checked.

## Goals

Automated tests for the user documentation.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Create a concept for testing the user doc automatically within CI/CD
- [ ] Remove or update not needed and obsolete chapters like: [test coverage](https://eclipse-ankaios.github.io/ankaios/0.4/development/test-coverage/), [unit test execution](https://eclipse-ankaios.github.io/ankaios/0.4/development/run-unit-tests/) => here it contains old commands and not the usage of the tools/*.sh scripts which shall be used to execute coverage and tests, because the tool scripts do preparation steps or containing important exclusions.
- [ ] Implement & test the concept

**Comment by windsource** [comment]
Is this a duplicate of #201?

**Comment by windsource** [comment]
Parts of this (checking dead links in CI) has already been handled in #477.

**Comment by windsource** [comment]
Best to use Copilot for testing user documentation (see previous comment) so closing this one.
