### ISSUE TITLE
Provide example automation for startup of Ankaios executables 

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#38]
## Description

Although targeted at automotive HPCs, Ankaios can actually be used in arbitrary systems. Especially small clusters with low resources would be a good target. 
To enable the usage of Ankaios in such environments, some automation for the startup of the executables would be helpful. As a start, systemd support can be added (because of the wide spread). Later other init systems could follow, e.g., [crinit](https://github.com/Elektrobit/crinit).

## Goals

Make Ankaios easy to use in a wider range of use cases.

## Final result

Automatic startup of Ankaios is supported in the install script.

### Summary

Automatic startup of Ankaios through systemd integration is provided in the install script.
The install script creates systemd service files Ankaios server and agent. In addition the install script installs a script for uninstalling Ankaios as well.

## Tasks

- [x] Extend install script to also install systemd unit files, see #61 
- [x] Extend install script to also install uninstall file, see #61 
- [x] Extend install script to create empty/sample state file, see #61 
- [x] Update documentation, see #61

**Comment by windsource** [comment]
In order for Ankaios server and and agent to start on system startup we should probably start them as root using systemd unit files for server and agent and maybe also one for podman (`podman.socket` only seems to be available in user scope). When podman service has been replaced by podman cli we do not need a unit file for podman anymore.

Then the install script needs to be extended to also install the systemd unit files and also enable and start the systemd services.

Ankaios server needs a startup state which we can place in `/etc/ank/state.yaml` or similar. The default startup state should be empty from my point of view.

Maybe we should also provide an uninstall script then.

**Comment by windsource** [comment]
As a first start I have created some systemd unit files that could do the job when stored in `/etc/systemd/system`.

`ank-server.service`:

```
[Unit]
Description=Ankaios server

[Service]
ExecStart=/usr/local/bin/ank-server --startup-config /etc/ank/state.yaml

[Install]
WantedBy=default.target
```

`podman.service`:

```
[Unit]
Description=Podman service

[Service]
ExecStart=/usr/bin/podman system service -t 0 unix:///tmp/podman.sock

[Install]
WantedBy=default.target
```

`ank-agent.service`:

```
[Unit]
Description=Ankaios agent
Requires=podman.service

[Service]
ExecStart=/usr/local/bin/ank-agent --name agent_A --podman-socket-path /tmp/podman.sock

[Install]
WantedBy=default.target
```

Then server and agent can easily be started as:

```shell
sudo systemctl start ank-server
sudo systemctl start ank-agent
```

**Comment by windsource** [comment]
Which name shall we use for the agent when installing systemd unit files? Should it be `agent_A` or maybe the hostname?

**Comment by krucod3** [comment]
We need options for the install script:
* install server and/or agent with default agent name( "") or specified agent name
* install only agent with specified name and url (default localhost:<port>) of the server

Maybe the state.yaml file can be prefilled with the structure and a commented out workload.
