### ISSUE TITLE
Adding automatic task list check in Pull Requests

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#42]
## Description

Currently, a PR can be merged without marking all tasks of the PR template as done.
To prevent this behavior, an automation shall be introduced that does not allow to merge the PR if a task of the PR template is not selected.

## Goals

Introduce an automation for preventing a merge of a Pull Request if the task list items are unchecked.

### Summary

The following GH Action https://github.com/Awayume/github-pr-tasklist-checker was accepted by the team.
It prevents merging PRs in case of not selected task list items of the PR template reliable.
Compared to other tested GH Actions within this issue, it works on-the-fly and has a short runtime.

### Tasks

- [x] Check if a GH Action can automate the task list check of the PR template and prevent merging in case of not selected list items
- [x] Test and compare different GH Actions
- [x] Integrate the config

**Comment by inf17101** [comment]
I have tried out different task checkers starting with those ones who have most stars and forks or available stable versions.
This one has a good gui for checking the unselected task list items, but has bugs and does not work when creating a fork of the ankaios project:
https://github.com/marketplace/actions/task-completed-checker (I have opened an issue about the bug (https://github.com/kentaro-m/task-completed-checker-action/issues/64) and I got some likes, so other people have the same issues, but the authors did still not reply...)

This one has bugs as well and does not work very well at all:
https://github.com/Shopify/task-list-checker

I found another action which is a little bit more unknown (not many stars and releases), but it does the stuff that we want. I presented it to the team and it was accepted:
https://github.com/Awayume/github-pr-tasklist-checker

The action will write a automated bot comment in the PR with the forgotten items of the PR task list.

I opened a PR...

**Comment by windsource** [comment]
@inf17101 Not sure if there is much benefit if if we add it to the documentation. The PR template already states:

> The PR shall be merged only if all of following items were checked. 

And if we add an automated check with this issues then it is sufficient IMHO.
