### ISSUE TITLE
Add itests or stests for uncovered SWDDs

### ISSUE THREAD

**Issue by lingnoi** [eclipse-ankaios/ankaios#56]
## Description

The following SWDDs are uncovered by itests or stests:
```text
not ok - 0/1>0>0/0 - swdd~agent-default-communication-grpc~1 (impl, -itest)
not ok - 0/3>0>0/0 - swdd~agent-manager-listens-requests-from-server~1 (impl, -itest, utest)
not ok - 0/1>0>0/0 - swdd~agent-sends-hello~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~agent-shall-use-interfaces-to-server~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~agent-supports-podman~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~cli-communication-over-middleware~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~communication-to-from-agent-middleware~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~communication-to-from-server-middleware~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-agent-connection-creates-execution-command-channel~1 (impl, -itest)
not ok - 0/7>0>0/0 - swdd~grpc-agent-connection-forwards-commands-to-server~1 (impl, -itest, utest)
not ok - 0/1>0>0/0 - swdd~grpc-agent-connection-forwards-hello-to-ankaios-server~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-agent-connection-responds-with-execution-channel-rx~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-agent-connection-sends-agent-gone~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-agent-connection-stores-execution-channel-tx~1 (impl, -itest)
not ok - 0/2>0>0/0 - swdd~grpc-client-connects-with-agent-hello~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-client-connects-with-unique-cli-connection-name~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-client-creates-state-change-channel~1 (impl, -itest)
not ok - 0/7>0>0/0 - swdd~grpc-client-forwards-commands-to-agent~1 (impl, -itest, utest)
not ok - 0/4>0>0/0 - swdd~grpc-client-forwards-commands-to-grpc-agent-connection~1 (impl, -itest, utest)
not ok - 0/1>0>0/0 - swdd~grpc-client-never-retries-cli-connection~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-client-outputs-error-server-connection-loss-for-cli-connection~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-client-outputs-error-server-unavailability-for-cli-connection~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-client-retries-connection~2 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-server-creates-agent-connection~1 (impl, -itest)
not ok - 0/4>0>0/0 - swdd~grpc-server-forwards-commands-to-grpc-client~1 (impl, -itest)
not ok - 0/1>0>0/0 - swdd~grpc-server-spawns-tonic-service~1 (impl, -itest)
not ok - 0/5>0>0/0 - swdd~podman-workload-creates-container~1 (impl, -stest, utest)
not ok - 0/3>0>0/0 - swdd~podman-workload-deletes-container~1 (impl, -stest, utest)
not ok - 0/4>0>0/0 - swdd~podman-workload-pulls-container~2 (impl, -stest, utest)
not ok - 0/5>0>0/0 - swdd~podman-workload-sends-workload-state~1 (impl, -itest, utest)
not ok - 0/5>0>0/0 - swdd~podman-workload-starts-container~1 (impl, -stest, utest)
not ok - 0/3>0>0/0 - swdd~podman-workload-stops-container~1 (impl, -stest, utest)
not ok - 0/1>0>0/0 - swdd~server-default-communication-grpc~1 (impl, -itest)
not ok - 0/2>0>0/0 - swdd~server-detects-changed-workload~1 (impl, -itest, utest)
not ok - 0/2>0>0/0 - swdd~server-detects-deleted-workload~1 (impl, -itest, utest)
not ok - 0/2>0>0/0 - swdd~server-detects-new-workload~1 (impl, -itest, utest)
```

## Goals

All SWDDs listed above are covered by itests or stests.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

`-itest` means itest is missing.
`-stest` means stest is missing.

- [ ]  `swdd~agent-default-communication-grpc~1 (impl, -itest)`
- [ ]  `swdd~agent-manager-listens-requests-from-server~1 (impl, -itest, utest)`
- [ ]  `swdd~agent-sends-hello~1 (impl, -itest)`
- [ ]  `swdd~agent-shall-use-interfaces-to-server~1 (impl, -itest)`
- [ ]  `swdd~agent-supports-podman~1 (impl, -itest)`
- [ ]  `swdd~cli-communication-over-middleware~1 (impl, -itest)`
- [ ]  `swdd~communication-to-from-agent-middleware~1 (impl, -itest)`
- [ ]  `swdd~communication-to-from-server-middleware~1 (impl, -itest)`
- [ ]  `swdd~grpc-agent-connection-creates-execution-command-channel~1 (impl, -itest)`
- [ ]  `swdd~grpc-agent-connection-forwards-commands-to-server~1 (impl, -itest, utest)`
- [ ]  `swdd~grpc-agent-connection-forwards-hello-to-ankaios-server~1 (impl, -itest)`
- [ ]  `swdd~grpc-agent-connection-responds-with-execution-channel-rx~1 (impl, -itest)`
- [ ]  `swdd~grpc-agent-connection-sends-agent-gone~1 (impl, -itest)`
- [ ]  `swdd~grpc-agent-connection-stores-execution-channel-tx~1 (impl, -itest)`
- [ ]  `swdd~grpc-client-connects-with-agent-hello~1 (impl, -itest)`
- [ ]  `swdd~grpc-client-connects-with-unique-cli-connection-name~1 (impl, -itest)`
- [ ]  `swdd~grpc-client-creates-state-change-channel~1 (impl, -itest)`
- [ ]  `swdd~grpc-client-forwards-commands-to-agent~1 (impl, -itest, utest)`
- [ ]  `swdd~grpc-client-forwards-commands-to-grpc-agent-connection~1 (impl, -itest, utest)`
- [ ]  `swdd~grpc-client-never-retries-cli-connection~1 (impl, -itest)`
- [ ]  `swdd~grpc-client-outputs-error-server-connection-loss-for-cli-connection~1 (impl, -itest)`
- [ ]  `swdd~grpc-client-outputs-error-server-unavailability-for-cli-connection~1 (impl, -itest)`
- [ ]  `swdd~grpc-client-retries-connection~2 (impl, -itest)`
- [ ]  `swdd~grpc-server-creates-agent-connection~1 (impl, -itest)`
- [ ]  `swdd~grpc-server-forwards-commands-to-grpc-client~1 (impl, -itest)`
- [ ]  `swdd~grpc-server-spawns-tonic-service~1 (impl, -itest)`
- [ ]  `swdd~podman-workload-creates-container~1 (impl, -stest, utest)`
- [ ]  `swdd~podman-workload-deletes-container~1 (impl, -stest, utest)`
- [ ]  `swdd~podman-workload-pulls-container~2 (impl, -stest, utest)`
- [ ]  `swdd~podman-workload-sends-workload-state~1 (impl, -itest, utest)`
- [ ]  `swdd~podman-workload-starts-container~1 (impl, -stest, utest)`
- [ ]  `swdd~podman-workload-stops-container~1 (impl, -stest, utest)`
- [ ]  `swdd~server-default-communication-grpc~1 (impl, -itest)`
- [ ]  `swdd~server-detects-changed-workload~1 (impl, -itest, utest)`
- [ ]  `swdd~server-detects-deleted-workload~1 (impl, -itest, utest)`
- [ ]  `swdd~server-detects-new-workload~1 (impl, -itest, utest)`

**Comment by krucod3** [comment]
Please generate a new list when starting to work on the ticket.

**Comment by inf17101** [comment]
I have used @christoph-hamm's branch with the authorization code + main merged and updated the list in the issue description (task list) above. Now, its more compared to the last list.

**Comment by inf17101** [comment]
@krucod3: Shall I concentrate on itest and stest only or also utests since a lot of utests are also uncovered?

**Comment by inf17101** [comment]
@krucod3: As discussed, I resolve only the uncovered utests and stests. For the itest we need an integration test concept first. I will create a new ticket for that

**Comment by inf17101** [comment]
The following swdds utest linkage needs to be fixed in a separate issue, because the utests are duplicating code at the moment and they all testing the same (the complete detailed change of `swdd~cli-watches-workloads~1`:

- swdd~cli-blocks-until-ankaios-server-responds-set-desired-state~2
- swdd~cli-provides-set-desired-state~1
-  swdd~cli-requests-update-state-with-watch~1
-  swdd~cli-requests-update-state-with-watch-error~1
-  swdd~cli-requests-update-state-with-watch-success~1

Better would be to move the wait_for_complete functionality in an own module that can be mocked easily and the detailed logic and chain of waiting is only test within the workload. All the other swdds expressing only that the cli shall wait and watch the changed workloads shall be unit tested by verifying that the function doing the wait logic is called (the mock of the new module can be used as an expectation then). This avoids code duplication and simplifies the linkage.

But like discussed with @krucod3, this shall be done in the future within an separate issue.

**Comment by inf17101** [comment]
I synced with Rares and we have fixed the linkage in his PR. `swdd~cli-provides-set-desired-state~1` and `swdd~cli-supports-yaml-to-set-desired-state~1` is fixed within #311 by adding a utest and linking it properly.

**Comment by krucod3** [comment]
What we cannot fix now is the itests as we don't have a concept for this yet. 
Otherwise we already fixes a lot of the problems for the stests and utests.

The ticket will be shifted to backlog as we cannot proceed further with it for now.
