### ISSUE TITLE
Use cargo-deny for license checks

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#59]
## Description

Currently the license of the dependencies is only manually checked.

## Goals

Use [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) to check the license of dependencies with every build and break the build when a dependency does not comply to the license we use.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] Add cargo-deny to the dev container
- [x] Create config `deny.toml`
- [x] Add to CI build

**Comment by windsource** [comment]
A first draft for `deny.toml`:

```toml
# Config file for cargo deny
# For all options see https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
]
private = { ignore = true }
exceptions = [{ name = "unicode-ident", allow = ["Unicode-DFS-2016"] }]
copyleft = "deny"

[bans]
multiple-versions = "allow"

[advisories]
vulnerability = "warn"
```

**Comment by inf17101** [comment]
> A first draft for `deny.toml`:
> 
> ```toml
> # Config file for cargo deny
> # For all options see https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml
> 
> [licenses]
> allow = [
>     "MIT",
>     "Apache-2.0",
>     "BSD-3-Clause",
> ]
> private = { ignore = true }
> exceptions = [{ name = "unicode-ident", allow = ["Unicode-DFS-2016"] }]
> copyleft = "deny"
> 
> [bans]
> multiple-versions = "allow"
> 
> [advisories]
> vulnerability = "warn"
> ```

Maybe we can add "BSD-2-Clause" as well as it is also compatible with Apache-2.0. I did some short research https://libguides.wvu.edu/c.php?g=1260463&p=9239129#:~:text=contributor's%20patent%20license.-,BSD%20Compatibility,GNU%2DGPL%20family%20of%20license.

**Comment by windsource** [comment]
@inf17101 Adding `BSD-2-Clause` makes sense is fine for me. I think there are some other licenses as well that we might use. In general I think the process might be that if someone adds a dependency and `cargo deny check` complains about a license then we need to check the license and add it to the whitelist in case it fits.

We should add `cargo deny check` to the CI build but it would be good to also execute it before commit to detect problems like license but also advisory problems early. But I am not sure to enforce a local execution. One idea is to have a makefile and add it to the build step such that we do not call `cargo build` but rather `make build` which then also calls `cargo deny check`.

**Comment by windsource** [comment]
When adding `BSD-2-Clause` I get a warning:

```
$ cargo deny check 
warning[license-not-encountered]: license was not encountered
  ┌─ /workspaces/ankaios/deny.toml:9:5
  │
9 │     "BSD-2-Clause"
  │     ^^^^^^^^^^^^^^ unmatched license allowance
```

So now I think we should only include licenses we really use and add others later on when we need them.
