### ISSUE TITLE
Configure self service with initial branch protection rules

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#71]
## Description

After we have enabled the selfservice via Gitlab Issue https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3805 and now trying to make strict branch protection rule for main branch, I have noticed that the workflow event triggering setting of the documentation wokflow (https://github.com/eclipse-ankaios/ankaios/blob/main/.github/workflows/documentation.yml) makes some trouble.

The problem is caused by the path-filter and branch-filter setting inside this workflow:

```
on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
      - 'api/proto/**'
      - '.github/workflows/documentation.yml'
  pull_request:
    paths:
      - 'doc/**'
      - 'api/proto/**'
      - '.github/workflows/documentation.yml'
```

If I configure the workflow as a required status check, then a PR is even blocked for merging if the PR does not change any of the files in the path-filter setting of the documentation workflow. The workflow is marked as pending and the PR is not allowed to be merged.

![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/08db66ba-2e01-49ce-a4b1-c255353386eb)

## Goals

Solve the problem, so that the documentation workflow runs and blocks the PR from merging if a doc file in the file-path setting was changed by a PR but also does not block other PRs from merging that are not changing any doc file.

### Summary

The self service was enabled with initial branch protection rules. Now, nobody can merge on main without a PR and status checks are required.

To fix the documentation workflow the workflow trigger condition was removed and integrated into a job conditional (because a skipped job does not mark a workflow as pending or not started). To fix this an additional job is created inside the documentation workflow that checks with a "path filter" GH action whether the documentation must be build or not in the pipeline. This prevents, that PRs are blocked when the documentation workflow is marked as required status check in the branch protection rules.

### Tasks

- [x] Figure out how the self service works
- [x] Configure branch protection rules
- [x] Extend the user documentation about the self service (links to self service documentation and general infos are enough)

**Comment by inf17101** [comment]
I tried to find a solution for this problem:

First with doing a research, and there are two workarounds (for me they seem like a hack :-D):
- This first one tries to solve this problem with a javascript script inside the workflow config: https://github.com/orgs/community/discussions/26857
- The second one tries to solve this problem by using a complementary workload definition: https://github.com/orgs/community/discussions/49124, The author set that there is a official workaround in the github docs available and he put the link into his posts. After following this link I noticed that the GH doc site has changed since his post and they have now removed the workaround and are saying strictly that a path-filer or branch-filter shall not be used at all when a workflow is defined as required status check for a PR. Here you can find the doc saying this : https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks

Besides the fact that I am not really happy with the above suggested solutions, I checked the docs again and it says that job if conditionals that are not executed due to the skip condition defined there are not blocking PRs from merging they are marked as passing. This means if we re-formulate the path-filter settings in the workflow event trigger configuration to a job skip conditional then the PR shall not be blocked from merging if it does not touch a file from the documentation itself.

Another alternative is to just not mark the documentation workflow as required, but then someone can merge a PR when changing the documentation wrongly...

**Comment by windsource** [comment]
The purpose of the documentation workflow for pull request is to check for syntax problems that might cause building the documentation fails. The only source of problem I could imaging is the `doc/mkdocs.yml`. I have never seen such a build break.
On the other hand the path filter should avoid unnecessary builds in case no documentation part has been changed. So either removing the path conditions or not require this build for PRs seems to be OK for me if this causes problems.

**Comment by windsource** [comment]
If choosing between both, than probably removing the path condition is probably more safe.

**Comment by inf17101** [comment]
I have been found an GH action that is able to do a path filter as job conditional https://github.com/dorny/paths-filter. GH does not block the PR if a workflow is skipped due to not matching job conditionals. 

This means if we move the path filter of the workflow conditional into a job conditional we are able to skip the deploy documentation job if no file matching the path filter was touched inside the PR.
