### ISSUE TITLE
Prepare the v0.2 release

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#83]
## Description

This ticket is for the code changes, e.g., versions, etc., needed to do the v0.2 release

## Goals

Prepare the v0.2 release

### Summary

The code is prepared to trigger the v0.2 release

### Tasks

- [x] Update versions to v0.2
- [x] Switch to musl to build statically linked binaries needed for the Ubuntu 20.04 and 22.04 support
- [x] Make sure debian packages work properly
- [x] Clarify support for `podman-kube` runtime on Ubuntu 20.04 LTS and Ubuntu 22.04 LTS.
- [x] Check and update (user) documentation
- [x] Update crates to remove security warnings (check with cargo-deny) - #98

**Comment by krucod3** [comment]
All done here.
